import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { CarFront, Check, ChevronLeft, ChevronRight, Clock3, Droplets, MessageCircle, Plus, RotateCcw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { getCurrentCompanyId } from "@/services/company";

export const Route=createFileRoute("/_authenticated/agenda")({component:AgendaPage});
type Service={id:string;name:string;price:number;estimated_duration:number;category:string|null;vehicle_category:string};
type Appointment={id:string;customer_name:string;customer_phone:string;vehicle_plate:string|null;appointment_time:string;status:string;total_price:number;total_duration:number;services:{id:string;name:string}[]};
const today=()=>new Date().toLocaleDateString("en-CA");
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statuses=[{key:"pending",label:"Aguardando",icon:Clock3},{key:"confirmed",label:"Em lavagem",icon:Droplets},{key:"completed",label:"Pronto",icon:Check},{key:"delivered",label:"Concluído",icon:CarFront}] as const;

function AgendaPage(){
 const [date,setDate]=useState(today());const [companyName,setCompanyName]=useState("empresa");const [items,setItems]=useState<Appointment[]>([]);const [services,setServices]=useState<Service[]>([]);const [capacity,setCapacity]=useState(2);const [slug,setSlug]=useState("lavapro");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);
 const [name,setName]=useState("");const [phone,setPhone]=useState("");const [category,setCategory]=useState("Hatch");const [plate,setPlate]=useState("");const [brand,setBrand]=useState("");const [model,setModel]=useState("");const [serviceIds,setServiceIds]=useState<string[]>([]);const [walkinTime,setWalkinTime]=useState("");const [slots,setSlots]=useState<string[]>([]);const [notes,setNotes]=useState("");
 const load=async()=>{
  try{setLoading(true);setError("");const companyId=await getCurrentCompanyId();
   const [companyRes,serviceRes]=await Promise.all([
    supabase.from("companies").select("name,public_booking_slug,simultaneous_capacity").eq("id",companyId).maybeSingle(),
    supabase.from("services").select("id,name,price,estimated_duration,category,vehicle_category").eq("company_id",companyId).eq("active",true).order("category").order("name")
   ]);
   if(companyRes.error)throw companyRes.error;if(serviceRes.error)throw serviceRes.error;setCompanyName(companyRes.data?.name??"empresa");setSlug(companyRes.data?.public_booking_slug??"");setCapacity(Math.max(1,companyRes.data?.simultaneous_capacity??2));setServices((serviceRes.data??[]) as Service[]);
   const r=await supabase.from("appointments").select("id,customer_name,customer_phone,vehicle_plate,appointment_time,status,total_price,total_duration,service:services(id,name)").eq("company_id",companyId).eq("appointment_date",date).neq("status","cancelled").order("appointment_time");
   if(r.error)throw r.error;const rows=r.data??[];const ids=rows.map(x=>x.id);const links=ids.length?await (supabase as any).from("appointment_services").select("appointment_id,service_id,price,duration_minutes,service:services(id,name)").in("appointment_id",ids):{data:[],error:null};if(links.error)throw links.error;
   const grouped=new Map<string,any[]>();for(const x of links.data??[])grouped.set(x.appointment_id,[...(grouped.get(x.appointment_id)??[]),x]);
   setItems(rows.map((x:any)=>{const ls=grouped.get(x.id)??[];return {...x,total_price:ls.length?ls.reduce((s:number,y:any)=>s+Number(y.price),0):Number(x.total_price??0),total_duration:ls.length?ls.reduce((s:number,y:any)=>s+Number(y.duration_minutes??60),0):Number(x.total_duration??0),services:ls.length?ls.map(y=>y.service).filter(Boolean):(x.service?[x.service]:[])}}));
  }catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar a agenda.");}finally{setLoading(false)}
 };
 useEffect(()=>{void load()},[date]);
 const compatible=useMemo(()=>services.filter(s=>s.vehicle_category==="all"||s.vehicle_category===category),[services,category]);
 useEffect(()=>{setServiceIds(p=>p.filter(id=>compatible.some(s=>s.id===id)));setWalkinTime("")},[category]);
 useEffect(()=>{if(!open||!serviceIds.length)return void setSlots([]);void(async()=>{const r=await (supabase as any).rpc("get_public_available_slots_multi",{_slug:slug,_date:date,_service_ids:serviceIds});if(r.error)setError(r.error.message);else setSlots((r.data??[]).map((x:any)=>x.slot.slice(0,5)))})()},[open,slug,date,serviceIds]);
 const resetForm=()=>{setName("");setPhone("");setCategory("Hatch");setPlate("");setBrand("");setModel("");setServiceIds([]);setWalkinTime("");setSlots([]);setNotes("")};
 const saveWalkin=async()=>{
  if(!name.trim()||phone.replace(/\D/g,"").length<8||!serviceIds.length||!walkinTime)return setError("Preencha nome, WhatsApp, serviço e horário.");
  try{setSaving(true);setError("");const companyId=await getCurrentCompanyId();const r=await (supabase as any).rpc("create_walk_in_appointment",{_company_id:companyId,_name:name.trim(),_phone:phone.trim(),_service_ids:serviceIds,_date:date,_time:walkinTime,_vehicle_category:category,_vehicle_plate:plate.trim()||null,_vehicle_brand:brand.trim()||null,_vehicle_model:model.trim()||null,_notes:notes.trim()||null});if(r.error)throw r.error;setOpen(false);resetForm();await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível criar o atendimento.")}finally{setSaving(false)}};
 const move=async(a:Appointment)=>{const next=a.status==="pending"?"confirmed":a.status==="confirmed"?"completed":a.status==="completed"?"delivered":null;if(!next)return;const now=new Date().toISOString();const patch:any={status:next,updated_at:now};if(next==="confirmed")patch.washing_at=now;if(next==="completed")patch.ready_at=now;if(next==="delivered")patch.completed_at=now;const r=await supabase.from("appointments").update(patch).eq("id",a.id);if(r.error)setError(r.error.message);else void load()};
 const cancel=async(a:Appointment)=>{if(!window.confirm("Cancelar este atendimento?"))return;const r=await supabase.from("appointments").update({status:"cancelled",updated_at:new Date().toISOString()}).eq("id",a.id);if(r.error)setError(r.error.message);else void load()};
 const whatsapp=(a:Appointment)=>{const phone=a.customer_phone.replace(/\D/g,"");if(phone.length<8)return;const msg=encodeURIComponent(`Olá, ${a.customer_name}! Seu veículo está pronto para retirada na ${companyName}. 🚗✨`);window.open(`https://wa.me/${phone.startsWith("55")?phone:"55"+phone}?text=${msg}`,"_blank","noopener,noreferrer")};
 return <div className="mx-auto max-w-7xl space-y-5 pb-10">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-primary"><Sparkles className="h-4 w-4"/>Painel de atendimento</div><h1 className="mt-1 text-3xl font-bold tracking-tight">Agenda</h1><p className="text-sm capitalize text-muted-foreground">{new Date(date+"T12:00:00").toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"})} · {capacity} vagas simultâneas</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="icon" onClick={()=>setDate(d=>{const x=new Date(d+"T12:00:00");x.setDate(x.getDate()-1);return x.toLocaleDateString("en-CA")})}><ChevronLeft/></Button><Button variant="outline" onClick={()=>setDate(today())}>Hoje</Button><Button variant="outline" size="icon" onClick={()=>setDate(d=>{const x=new Date(d+"T12:00:00");x.setDate(x.getDate()+1);return x.toLocaleDateString("en-CA")})}><ChevronRight/></Button><Button onClick={()=>{setError("");setOpen(true)}}><Plus className="mr-2 h-4 w-4"/>Atendimento</Button></div></div>
  {error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{statuses.map(s=>{const list=items.filter(a=>a.status===s.key);const Icon=s.icon;return <Card key={s.key} className="rounded-2xl border-border/60 shadow-sm"><CardHeader className="pb-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2 font-semibold"><Icon className="h-4 w-4 text-primary"/>{s.label}</div><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-bold">{list.length}</span></div></CardHeader><CardContent className="space-y-3">{loading?<div className="h-24 animate-pulse rounded-xl bg-muted"/>:list.length===0?<p className="py-8 text-center text-xs text-muted-foreground">Nenhum veículo</p>:list.map(a=><div key={a.id} className="rounded-xl border bg-card p-3 shadow-sm"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{a.customer_name}</p><p className="text-xs text-muted-foreground">{a.vehicle_plate||"Placa não informada"} · {a.appointment_time.slice(0,5)}</p></div><span className="text-sm font-bold">{money(a.total_price)}</span></div><p className="mt-2 text-xs text-muted-foreground">{a.services.map(x=>x.name).join(" + ")||"Serviço"} · {a.total_duration} min</p><div className="mt-3 flex gap-2">{a.status!=="delivered"&&<Button size="sm" className="flex-1" onClick={()=>void move(a)}>{a.status==="pending"?"Iniciar lavagem":a.status==="confirmed"?"Marcar pronto":"Concluir"}</Button>}{a.status==="completed"&&<Button size="sm" variant="outline" onClick={()=>whatsapp(a)}><MessageCircle className="mr-1 h-4 w-4"/>WhatsApp</Button>}{a.status==="pending"&&<Button size="sm" variant="ghost" onClick={()=>void cancel(a)}>Cancelar</Button>}</div></div>)}</CardContent></Card>})}</div>
  <div className="flex items-center justify-between rounded-xl border border-border/60 bg-muted/30 px-4 py-3 text-xs text-muted-foreground"><span className="flex items-center gap-2"><RotateCcw className="h-4 w-4"/>Agendamentos online e presenciais usam a mesma agenda.</span><Link to="/configuracoes" className="font-semibold text-primary">Configurações</Link></div>
  <Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v)resetForm()}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Novo atendimento presencial</DialogTitle></DialogHeader><div className="space-y-5">
   <div className="grid gap-4 sm:grid-cols-2"><div><Label>Nome *</Label><Input className="mt-2" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do cliente"/></div><div><Label>WhatsApp *</Label><Input className="mt-2" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(48) 99999-9999"/></div></div>
   <div><Label>Categoria do veículo *</Label><div className="mt-2 grid grid-cols-3 gap-2">{["Hatch","Sedan","SUV/Picape"].map(v=><button type="button" key={v} onClick={()=>setCategory(v)} className={`rounded-xl border p-3 text-sm font-semibold ${category===v?"border-primary bg-primary/10 text-primary":"border-border"}`}>{v}</button>)}</div></div>
   <div><Label>Serviços *</Label><div className="mt-2 grid gap-2">{compatible.map(s=><label key={s.id} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 ${serviceIds.includes(s.id)?"border-primary bg-primary/10":"border-border"}`}><input type="checkbox" checked={serviceIds.includes(s.id)} onChange={()=>setServiceIds(p=>p.includes(s.id)?p.filter(id=>id!==s.id):[...p,s.id])} className="h-4 w-4 accent-primary"/><span className="flex-1 text-sm font-medium">{s.name}</span><span className="text-xs text-muted-foreground">{s.estimated_duration} min · {money(Number(s.price))}</span></label>)}</div></div>
   <div className="grid gap-4 sm:grid-cols-2"><div><Label>Data</Label><Input className="mt-2" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div><Label>Horário *</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={walkinTime} onChange={e=>setWalkinTime(e.target.value)} disabled={!serviceIds.length}><option value="">Selecione</option>{slots.map(s=><option key={s} value={s}>{s}</option>)}</select></div></div>
   <div className="rounded-xl border bg-muted/20 p-4"><p className="mb-3 text-sm font-semibold">Veículo</p><div className="grid gap-3 sm:grid-cols-3"><div><Label>Placa</Label><Input className="mt-2" value={plate} onChange={e=>setPlate(e.target.value.toUpperCase())}/></div><div><Label>Marca</Label><Input className="mt-2" value={brand} onChange={e=>setBrand(e.target.value)}/></div><div><Label>Modelo</Label><Input className="mt-2" value={model} onChange={e=>setModel(e.target.value)}/></div></div></div>
   <div><Label>Observações</Label><Textarea className="mt-2" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Opcional"/></div>
   <div className="flex items-center justify-between rounded-xl bg-primary/5 p-4"><span className="text-sm text-muted-foreground">{serviceIds.length} serviço(s) selecionado(s)</span><span className="font-bold">{money(serviceIds.reduce((sum,id)=>sum+Number(services.find(s=>s.id===id)?.price??0),0))}</span></div>
   <Button className="w-full" onClick={()=>void saveWalkin()} disabled={saving||!walkinTime}>{saving?"Registrando...":"Registrar atendimento"}</Button>
  </div></DialogContent></Dialog>
 </div>
}
