import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Car, Clock3, MessageCircle, Search, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { getCurrentCompanyId } from "@/services/company";

export const Route=createFileRoute("/_authenticated/clientes")({component:ClientesPage});
type Customer={id:string;name:string;phone:string|null;email:string|null;notes:string|null;created_at:string};
type Vehicle={id:string;plate:string|null;brand:string|null;model:string|null;category:string};
type Visit={id:string;appointment_date:string;appointment_time:string;status:string;total_price:number;total_duration:number;source:string;vehicle_plate:string|null;services:string[]};

function ClientesPage(){
 const [customers,setCustomers]=useState<Customer[]>([]);const [inactive,setInactive]=useState<Customer[]>([]);const [selected,setSelected]=useState<Customer|null>(null);const [vehicles,setVehicles]=useState<Vehicle[]>([]);const [visits,setVisits]=useState<Visit[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [detailLoading,setDetailLoading]=useState(false);const [error,setError]=useState("");
 const load=async()=>{try{setLoading(true);setError("");const id=await getCurrentCompanyId();const r=await supabase.from("customers").select("id,name,phone,email,notes,created_at").eq("company_id",id).order("name");if(r.error)throw r.error;setCustomers((r.data??[]) as Customer[]);const all=(r.data??[]) as Customer[];const cutoff=new Date();cutoff.setDate(cutoff.getDate()-60);const ap=await supabase.from("appointments").select("customer_id,appointment_date,status").eq("company_id",id).neq("status","cancelled").order("appointment_date",{ascending:false});if(ap.error)throw ap.error;const latest=new Map<string,string>();for(const a of ap.data??[]){if(!latest.has(a.customer_id))latest.set(a.customer_id,a.appointment_date)}setInactive(all.filter(c=>{const d=latest.get(c.id);return d?new Date(d+"T12:00:00")<cutoff:true}).slice(0,20));}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os clientes.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>customers.filter(c=>{const q=query.toLowerCase().trim();return !q||c.name.toLowerCase().includes(q)||(c.phone??"").replace(/\D/g,"").includes(q.replace(/\D/g,""))}),[customers,query]);
 const openCustomer=async(c:Customer)=>{try{setSelected(c);setDetailLoading(true);const [v,a]=await Promise.all([supabase.from("vehicles").select("id,plate,brand,model,category").eq("company_id",await getCurrentCompanyId()).eq("customer_id",c.id).order("created_at",{ascending:false}),supabase.from("appointments").select("id,appointment_date,appointment_time,status,total_price,total_duration,source,vehicle_plate").eq("customer_id",c.id).order("appointment_date",{ascending:false}).order("appointment_time",{ascending:false}).limit(30)]);if(v.error)throw v.error;if(a.error)throw a.error;const ids=(a.data??[]).map(x=>x.id);const links=ids.length?await (supabase as any).from("appointment_services").select("appointment_id,service:services(name)").in("appointment_id",ids):{data:[],error:null};if(links.error)throw links.error;const names=new Map<string,string[]>();for(const x of links.data??[])names.set(x.appointment_id,[...(names.get(x.appointment_id)??[]),x.service?.name].filter(Boolean));setVehicles((v.data??[]) as Vehicle[]);setVisits((a.data??[]).map((x:any)=>({...x,total_price:Number(x.total_price??0),services:names.get(x.id)??[]})))}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar o histórico.")}finally{setDetailLoading(false)}};
 const spent=visits.reduce((s,v)=>s+(v.status==="cancelled"?0:v.total_price),0);
 const whatsapp=(phone:string|null,message?:string)=>{const p=(phone??"").replace(/\D/g,"");if(p.length<8)return;window.open("https://wa.me/"+(p.startsWith("55")?p:"55"+p)+(message?"?text="+encodeURIComponent(message):""),"_blank","noopener,noreferrer")};
 return <div className="mx-auto max-w-6xl space-y-6 pb-10">
  <div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Relacionamento</p><h1 className="mt-1 text-3xl font-bold">Clientes</h1><p className="text-sm text-muted-foreground">Clientes, veículos e histórico de atendimentos.</p></div>
  {error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
  <Card className="rounded-2xl"><CardContent className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Clientes inativos</p><p className="text-xs text-muted-foreground">Sem atendimento nos últimos 60 dias · {inactive.length} cliente(s)</p></div><Button variant="outline" size="sm" disabled={!inactive.length} onClick={()=>inactive.forEach(c=>{if(c.phone)whatsapp(c.phone,`Olá ${c.name.split(" ")[0]}! Sentimos sua falta 😊 Que tal agendar uma nova limpeza para seu veículo?`);})}><MessageCircle className="mr-2 h-4 w-4"/>Enviar WhatsApp</Button></div><div className="relative mt-3"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar por nome ou WhatsApp..." value={query} onChange={e=>setQuery(e.target.value)}/></div></CardContent></Card>
  <div className="grid gap-4 lg:grid-cols-[1fr_1.15fr]">
   <Card className="rounded-2xl"><CardContent className="p-0"><div className="border-b px-5 py-4 text-sm font-semibold">{filtered.length} cliente(s)</div>{loading?<p className="p-6 text-sm text-muted-foreground">Carregando...</p>:filtered.length===0?<p className="p-8 text-center text-sm text-muted-foreground">Nenhum cliente encontrado.</p>:<div className="divide-y">{filtered.map(c=><button key={c.id} type="button" onClick={()=>void openCustomer(c)} className={`flex w-full items-center gap-3 p-4 text-left transition hover:bg-muted/50 ${selected?.id===c.id?"bg-primary/5":""}`}><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary"><UserRound className="h-4 w-4"/></div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{c.name}</p><p className="truncate text-xs text-muted-foreground">{c.phone||"WhatsApp não informado"}</p></div></button>)}</div>}</CardContent></Card>
   <Card className="rounded-2xl"><CardContent className="p-5">{!selected?<div className="flex min-h-[360px] flex-col items-center justify-center text-center text-muted-foreground"><UserRound className="mb-3 h-10 w-10"/><p className="font-medium">Selecione um cliente</p><p className="mt-1 text-xs">Veja veículos e histórico de serviços.</p></div>:<div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-sm text-muted-foreground">{selected.phone||"WhatsApp não informado"}</p></div>{selected.phone&&<div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>whatsapp(selected.phone)}><MessageCircle className="mr-2 h-4 w-4"/>WhatsApp</Button><Button variant="outline" size="sm" onClick={()=>whatsapp(selected.phone,`Olá ${selected.name.split(" ")[0]}! Seu veículo está pronto para retirada. 🚗`)}>Veículo pronto</Button><Button variant="outline" size="sm" onClick={()=>whatsapp(selected.phone,`Olá ${selected.name.split(" ")[0]}! Podemos confirmar seu próximo atendimento?`)}>Confirmar</Button></div>}</div>{detailLoading?<p className="text-sm text-muted-foreground">Carregando histórico...</p>:<><div className="grid grid-cols-3 gap-2"><Stat label="Atendimentos" value={String(visits.filter(v=>v.status!=="cancelled").length)}/><Stat label="Total gasto" value={money(spent)}/><Stat label="Veículos" value={String(vehicles.length)}/></div><div><h3 className="mb-2 flex items-center gap-2 font-semibold"><Car className="h-4 w-4"/>Veículos</h3>{vehicles.length?<div className="grid gap-2 sm:grid-cols-2">{vehicles.map(v=><div key={v.id} className="rounded-xl border p-3"><p className="font-semibold">{v.plate||"Sem placa"}</p><p className="text-xs text-muted-foreground">{[v.brand,v.model,v.category].filter(Boolean).join(" · ")}</p></div>)}</div>:<p className="text-sm text-muted-foreground">Nenhum veículo cadastrado.</p>}</div><div><h3 className="mb-2 flex items-center gap-2 font-semibold"><Clock3 className="h-4 w-4"/>Histórico</h3>{visits.length?<div className="divide-y rounded-xl border">{visits.map(v=><div key={v.id} className="flex flex-col gap-2 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{v.services.join(" + ")||"Serviço"}</p><p className="text-xs text-muted-foreground">{new Date(v.appointment_date+"T12:00:00").toLocaleDateString("pt-BR")} · {v.appointment_time.slice(0,5)} · {v.vehicle_plate||"Sem placa"}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-muted px-2 py-1 text-[11px]">{statusLabel(v.status)}</span><span className="font-semibold">{money(v.total_price)}</span></div></div>)}</div>:<p className="text-sm text-muted-foreground">Nenhum atendimento registrado.</p>}</div></>}</div>}</CardContent></Card>
  </div>
 </div>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-muted/20 p-3"><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>}
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statusLabel=(s:string)=>s==="pending"?"Aguardando":s==="confirmed"?"Em lavagem":s==="completed"?"Pronto":s==="delivered"?"Concluído":"Cancelado";
