import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { getCurrentCompanyId } from "@/services/company";

export const Route=createFileRoute("/_authenticated/equipe")({component:EquipePage});
type Profile={id:string;user_id:string;full_name:string|null;email:string|null;role:"owner"|"admin"|"manager"|"employee";active:boolean};
const labels:Record<Profile["role"],string>={owner:"Proprietário",admin:"Administrador",manager:"Gerente",employee:"Atendente"};
function EquipePage(){
 const [items,setItems]=useState<Profile[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);const company=await getCurrentCompanyId();const r=await supabase.from("profiles").select("id,user_id,full_name,email,role,active").eq("company_id",company).order("created_at");if(r.error)throw r.error;setItems((r.data??[]) as Profile[])}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar a equipe.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const update=async(id:string,field:"role"|"active",value:string|boolean)=>{const r=await (supabase.from("profiles") as any).update({[field]:value,updated_at:new Date().toISOString()}).eq("id",id);if(r.error)setError(r.error.message);else void load()};
 return <div className="mx-auto max-w-5xl space-y-6 pb-10"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Administração</p><h1 className="mt-1 text-3xl font-bold">Equipe e permissões</h1><p className="text-sm text-muted-foreground">Controle os papéis e o acesso dos usuários da empresa.</p></div>{error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}<Card className="rounded-2xl"><CardHeader><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Usuários da empresa</h2><p className="text-sm text-muted-foreground">Proprietário, administrador, gerente e atendente.</p></div></div></CardHeader><CardContent>{loading?<p className="py-8 text-center text-sm text-muted-foreground">Carregando...</p>:items.length===0?<p className="py-8 text-center text-sm text-muted-foreground">Nenhum usuário vinculado.</p>:<div className="divide-y">{items.map(p=><div key={p.id} className="flex flex-col gap-4 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary"><UserRound className="h-4 w-4"/></div><div><p className="font-semibold">{p.full_name||p.email||"Usuário"}</p><p className="text-xs text-muted-foreground">{p.email||"E-mail não informado"} · {p.active?"Ativo":"Inativo"}</p></div></div><div className="flex flex-wrap items-center gap-2"><select value={p.role} disabled={p.role==="owner"} onChange={e=>void update(p.id,"role",e.target.value)} className="h-9 rounded-md border bg-background px-3 text-sm">{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{p.role!=="owner"&&<Button size="sm" variant={p.active?"outline":"default"} onClick={()=>void update(p.id,"active",!p.active)}>{p.active?"Desativar":"Ativar"}</Button>}</div></div>)}</div>}<div className="mt-5 rounded-xl bg-muted/40 p-4 text-sm text-muted-foreground">A criação de novas contas deve passar pela autenticação do Supabase. Esta tela administra usuários já vinculados à empresa e não expõe chaves administrativas no navegador.</div></CardContent></Card></div>
}
