import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CarFront, CircleDollarSign, TrendingUp } from "lucide-react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { getCurrentCompanyId } from "@/services/company";

export const Route=createFileRoute("/_authenticated/financeiro")({component:FinanceiroPage});
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const today=()=>new Date().toLocaleDateString("en-CA");
function FinanceiroPage(){
 const [date,setDate]=useState(today());const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const [month,setMonth]=useState(today().slice(0,7));
 useEffect(()=>{void(async()=>{try{setLoading(true);setError("");const id=await getCurrentCompanyId();const start=month+"-01";const d=new Date(start+"T12:00:00");d.setMonth(d.getMonth()+1,0);const end=d.toLocaleDateString("en-CA");const r=await supabase.from("appointments").select("id,customer_name,appointment_date,appointment_time,total_price,status").eq("company_id",id).gte("appointment_date",start).lte("appointment_date",end).eq("status","delivered").order("appointment_date",{ascending:false}).order("appointment_time",{ascending:false});if(r.error)throw r.error;setRows(r.data??[])}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar o financeiro.")}finally{setLoading(false)}})()},[month]);
 const monthRevenue=rows.reduce((s,r)=>s+Number(r.total_price??0),0);const monthCount=rows.length;const ticket=monthCount?monthRevenue/monthCount:0;const dayRows=rows.filter(r=>r.appointment_date===date);const dayRevenue=dayRows.reduce((s,r)=>s+Number(r.total_price??0),0);
 return <div className="mx-auto max-w-6xl space-y-6 pb-10"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Gestão</p><h1 className="mt-1 text-3xl font-bold">Financeiro</h1><p className="text-sm text-muted-foreground">Faturamento baseado nos atendimentos concluídos.</p></div>{error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}<div className="flex flex-wrap gap-3"><div><label className="mb-1 block text-xs font-medium text-muted-foreground">Mês</label><Input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><div><label className="mb-1 block text-xs font-medium text-muted-foreground">Dia</label><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div>
 <div className="grid gap-4 md:grid-cols-3"><Metric icon={CircleDollarSign} label="Faturamento do mês" value={loading?"—":money(monthRevenue)}/><Metric icon={CarFront} label="Serviços realizados" value={loading?"—":String(monthCount)}/><Metric icon={TrendingUp} label="Ticket médio" value={loading?"—":money(ticket)}/></div>
 <Card className="rounded-2xl"><CardHeader><div className="flex items-center justify-between"><div><h2 className="font-semibold">Resumo do dia</h2><p className="text-xs text-muted-foreground">{new Date(date+"T12:00:00").toLocaleDateString("pt-BR")}</p></div><span className="text-xl font-bold">{money(dayRevenue)}</span></div></CardHeader><CardContent>{dayRows.length===0?<p className="text-sm text-muted-foreground">Nenhum atendimento concluído neste dia.</p>:<div className="divide-y">{dayRows.map(r=><div key={r.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-medium">{r.customer_name}</p><p className="text-xs text-muted-foreground">{r.appointment_time.slice(0,5)}</p></div><span className="font-semibold">{money(Number(r.total_price??0))}</span></div>)}</div>}</CardContent></Card></div>
}
function Metric({icon:Icon,label,value}:{icon:typeof CircleDollarSign;label:string;value:string}){return <Card className="rounded-2xl"><CardContent className="p-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5"/></div><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></CardContent></Card>}
