import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ClipboardList } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { getCurrentCompanyId } from "@/services/company";

export const Route=createFileRoute("/_authenticated/ordens")({component:OrdensPage});
type Customer={id:string;name:string}; type Vehicle={id:string;customer_id:string;plate:string;brand:string|null;model:string|null}; type Service={id:string;name:string;price:number;estimated_duration:number|null}; type Order={id:string;customer_id:string|null;vehicle_id:string|null;status:string;subtotal:number;discount:number;total:number;notes:string|null;created_at:string;customer?:Customer|null;vehicle?:Vehicle|null};
const statusLabels:Record<string,string>={pending:"Pendente",in_progress:"Em andamento",completed:"Concluída",delivered:"Entregue",cancelled:"Cancelada"};
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function OrdensPage(){
 const [orders,setOrders]=useState<Order[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[services,setServices]=useState<Service[]>([]);
 const [customerId,setCustomerId]=useState(""),[vehicleId,setVehicleId]=useState(""),[serviceId,setServiceId]=useState(""),[qty,setQty]=useState("1"),[discount,setDiscount]=useState("0"),[notes,setNotes]=useState("");
 const [statusFilter,setStatusFilter]=useState("all"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);const company=await getCurrentCompanyId();const [o,c,v,s]=await Promise.all([supabase.from("service_orders").select("id,customer_id,vehicle_id,status,subtotal,discount,total,notes,created_at,customer:customers(id,name),vehicle:vehicles(id,customer_id,plate,brand,model)").eq("company_id",company).order("created_at",{ascending:false}),supabase.from("customers").select("id,name").eq("company_id",company).order("name"),supabase.from("vehicles").select("id,customer_id,plate,brand,model").eq("company_id",company).order("plate"),supabase.from("services").select("id,name,price,estimated_duration").eq("company_id",company).eq("active",true).order("name")]);for(const r of [o,c,v,s])if(r.error)throw r.error;setOrders((o.data??[]) as any);setCustomers((c.data??[]) as Customer[]);setVehicles((v.data??[]) as Vehicle[]);setServices((s.data??[]) as Service[])}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar as ordens.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const customerVehicles=useMemo(()=>vehicles.filter(v=>!customerId||v.customer_id===customerId),[vehicles,customerId]);
 const selectedService=services.find(s=>s.id===serviceId);const base=Number(selectedService?.price??0)*Math.max(1,Number(qty)||1);const total=Math.max(0,base-Math.max(0,Number(discount)||0));
 const create=async()=>{if(!customerId||!serviceId)return setError("Informe cliente e serviço.");try{setSaving(true);setError("");const company_id=await getCurrentCompanyId();const subtotal=base;const order=await supabase.from("service_orders").insert({company_id,customer_id:customerId,vehicle_id:vehicleId||null,status:"pending",subtotal,discount:Number(discount)||0,total,notes:notes.trim()||null}).select("id").single();if(order.error)throw order.error;const item=await supabase.from("service_order_items").insert({company_id,service_order_id:order.data.id,service_id:serviceId,quantity:Math.max(1,Number(qty)||1),unit_price:Number(selectedService?.price??0),total:subtotal});if(item.error)throw item.error;setCustomerId("");setVehicleId("");setServiceId("");setQty("1");setDiscount("0");setNotes("");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível criar a ordem.")}finally{setSaving(false)}};
 const updateStatus=async(o:Order,status:string)=>{const now=new Date().toISOString();const payload:any={status,updated_at:now};if(status==="in_progress")payload.started_at=now;if(status==="completed")payload.completed_at=now;const r=await supabase.from("service_orders").update(payload).eq("id",o.id);if(r.error)setError(r.error.message);else void load()};
 const filtered=orders.filter(o=>statusFilter==="all"||o.status===statusFilter);
 return <div className="mx-auto max-w-7xl space-y-6 pb-10"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Operação</p><h1 className="mt-1 text-3xl font-bold">Ordens de serviço</h1><p className="text-sm text-muted-foreground">Controle do atendimento, serviços, valores e histórico.</p></div>{error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
 <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><Card className="rounded-2xl"><CardHeader><h2 className="font-semibold">Nova ordem de serviço</h2></CardHeader><CardContent className="space-y-4"><div><Label>Cliente *</Label><select value={customerId} onChange={e=>{setCustomerId(e.target.value);setVehicleId("")}} className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecione...</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><Label>Veículo</Label><select value={vehicleId} onChange={e=>setVehicleId(e.target.value)} className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Sem veículo</option>{customerVehicles.map(v=><option key={v.id} value={v.id}>{v.plate} · {[v.brand,v.model].filter(Boolean).join(" ")}</option>)}</select></div><div><Label>Serviço *</Label><select value={serviceId} onChange={e=>setServiceId(e.target.value)} className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecione...</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} · {money(Number(s.price))}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><Label>Quantidade</Label><Input className="mt-2" type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/></div><div><Label>Desconto</Label><Input className="mt-2" type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></div></div><div><Label>Observações</Label><Input className="mt-2" value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="rounded-xl bg-muted/40 p-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><strong>{money(base)}</strong></div><div className="mt-1 flex justify-between text-base"><span>Total</span><strong>{money(total)}</strong></div></div><Button className="w-full" onClick={()=>void create()} disabled={saving}>{saving?"Criando...":"Criar ordem"}</Button></CardContent></Card>
 <Card className="rounded-2xl"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{filtered.length} ordem(ns)</h2><p className="text-sm text-muted-foreground">Acompanhe o ciclo de cada atendimento.</p></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="all">Todos</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></CardHeader><CardContent>{loading?<p className="py-8 text-center text-sm text-muted-foreground">Carregando...</p>:filtered.length===0?<div className="py-12 text-center text-muted-foreground"><ClipboardList className="mx-auto mb-3 h-10 w-10"/><p>Nenhuma ordem encontrada.</p></div>:<div className="space-y-3">{filtered.map(o=><div key={o.id} className="rounded-2xl border p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{o.customer?.name??"Cliente"}{o.vehicle?.plate?" · "+o.vehicle.plate:""}</p><p className="text-xs text-muted-foreground">{new Date(o.created_at).toLocaleString("pt-BR")} · {statusLabels[o.status]??o.status}</p></div><div className="flex items-center gap-2"><span className="font-bold">{money(Number(o.total))}</span><select value={o.status} onChange={e=>void updateStatus(o,e.target.value)} className="h-9 rounded-md border bg-background px-2 text-xs">{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div><p className="mt-2 text-sm text-muted-foreground">{o.notes||"Sem observações."}</p></div>)}</div>}</CardContent></Card></div></div>
}
