import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { BarChart3, CalendarDays, CarFront, CircleDollarSign, Users } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { getCurrentCompanyId } from "@/services/company";

export const Route=createFileRoute("/_authenticated/relatorios")({component:RelatoriosPage});
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function RelatoriosPage(){
 const [month,setMonth]=useState(new Date().toLocaleDateString("en-CA").slice(0,7));const [rows,setRows]=useState<any[]>([]);const [customers,setCustomers]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{void(async()=>{try{setLoading(true);const id=await getCurrentCompanyId();const start=month+"-01";const d=new Date(start+"T12:00:00");d.setMonth(d.getMonth()+1,0);const end=d.toLocaleDateString("en-CA");const [a,c]=await Promise.all([supabase.from("appointments").select("id,customer_id,customer_name,appointment_date,status,total_price,total_duration,vehicle_plate").eq("company_id",id).gte("appointment_date",start).lte("appointment_date",end),supabase.from("customers").select("id,created_at").eq("company_id",id).gte("created_at",start+"T00:00:00").lte("created_at",end+"T23:59:59")]);if(a.error)throw a.error;if(c.error)throw c.error;setRows(a.data??[]);setCustomers(c.data??[])}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os relatórios.")}finally{setLoading(false)}})()},[month]);
 const valid=rows.filter(r=>r.status!=="cancelled");const revenue=valid.reduce((s,r)=>s+Number(r.total_price||0),0);const services=valid.length;const ticket=services?revenue/services:0;const completed=valid.filter(r=>["completed","delivered"].includes(r.status)).length;const unique=new Set(valid.map(r=>r.customer_id).filter(Boolean)).size;
 const byDay=useMemo(()=>{const m=new Map<string,number>();for(const r of valid)m.set(r.appointment_date,(m.get(r.appointment_date)||0)+Number(r.total_price||0));return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0]))},[valid]);const max=Math.max(1,...byDay.map(x=>x[1]));
 return <div className="mx-auto max-w-6xl space-y-6 pb-10"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Análise</p><h1 className="mt-1 text-3xl font-bold">Relatórios</h1><p className="text-sm text-muted-foreground">Indicadores operacionais e financeiros do período.</p></div>{error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}<div className="w-fit"><label className="mb-1 block text-xs font-medium text-muted-foreground">Mês analisado</label><Input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric icon={CircleDollarSign} label="Faturamento" value={loading?"—":money(revenue)}/><Metric icon={CalendarDays} label="Atendimentos" value={loading?"—":String(services)}/><Metric icon={BarChart3} label="Concluídos" value={loading?"—":String(completed)}/><Metric icon={Users} label="Clientes atendidos" value={loading?"—":String(unique)}/><Metric icon={CarFront} label="Ticket médio" value={loading?"—":money(ticket)}/></div>
 <div className="grid gap-4 lg:grid-cols-[1.35fr_1fr]"><Card className="rounded-2xl"><CardContent className="p-5"><h2 className="font-bold">Faturamento diário</h2><p className="mb-5 text-xs text-muted-foreground">Distribuição por dia no mês selecionado</p>{byDay.length?<div className="flex h-56 items-end gap-2 overflow-x-auto pb-5">{byDay.map(([day,value])=><div key={day} className="flex min-w-10 flex-1 flex-col items-center justify-end gap-1"><span className="text-[10px] font-semibold">{money(value)}</span><div className="w-full rounded-t-lg bg-primary/70" style={{height:Math.max(8,Math.round(value/max*150))}}/><span className="text-[10px] text-muted-foreground">{day.slice(8,10)}</span></div>)}</div>:<p className="text-sm text-muted-foreground">Sem dados no período.</p>}</CardContent></Card>
 <Card className="rounded-2xl"><CardContent className="p-5"><h2 className="font-bold">Resumo</h2><div className="mt-4 space-y-3">{[["Novos clientes",customers.length],["Atendimentos cancelados",rows.filter(r=>r.status==="cancelled").length],["Duração média",services?Math.round(valid.reduce((s,r)=>s+Number(r.total_duration||0),0)/services)+" min":"0 min"]].map(([label,value])=><div key={String(label)} className="flex items-center justify-between border-b py-3 last:border-0"><span className="text-sm text-muted-foreground">{label}</span><strong>{value}</strong></div>)}</div></CardContent></Card></div>
 </div>
}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <Card className="rounded-2xl"><CardContent className="p-4"><Icon className="h-5 w-5 text-primary"/><p className="mt-3 text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-black">{value}</p></CardContent></Card>}
