import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { getCurrentCompanyId } from "@/services/company";

export const Route=createFileRoute("/_authenticated/servicos")({component:ServicosPage});
type Service={id:string;name:string;description:string|null;price:number;estimated_duration:number|null;category:string|null;vehicle_category:string;active:boolean};
const vehicleOptions=[["all","Todos"],["Hatch","Hatch"],["Sedan","Sedan"],["SUV/Picape","SUV/Picape"]];
function ServicosPage(){
 const [items,setItems]=useState<Service[]>([]);const [editing,setEditing]=useState<string|null>(null);const [name,setName]=useState("");const [description,setDescription]=useState("");const [price,setPrice]=useState("");const [duration,setDuration]=useState("60");const [category,setCategory]=useState("Lavagem");const [vehicle,setVehicle]=useState("all");const [error,setError]=useState("");const [saving,setSaving]=useState(false);
 const load=async()=>{const id=await getCurrentCompanyId();const r=await supabase.from("services").select("id,name,description,price,estimated_duration,category,vehicle_category,active").eq("company_id",id).order("active",{ascending:false}).order("name");if(r.error)setError(r.error.message);else setItems((r.data??[]) as Service[])};
 useEffect(()=>{void load()},[]);
 const clear=()=>{setEditing(null);setName("");setDescription("");setPrice("");setDuration("60");setCategory("Lavagem");setVehicle("all")};
 const save=async()=>{if(!name.trim())return setError("Informe o nome do serviço.");const id=await getCurrentCompanyId();setSaving(true);setError("");const payload={name:name.trim(),description:description.trim()||null,price:Number(price.replace(",","."))||0,estimated_duration:Math.max(5,Number(duration)||60),category,vehicle_category:vehicle,active:true,updated_at:new Date().toISOString(),company_id:id};const r=editing?await supabase.from("services").update(payload).eq("id",editing):await supabase.from("services").insert(payload);if(r.error)setError(r.error.message);else{clear();await load()}setSaving(false)};
 const edit=(s:Service)=>{setEditing(s.id);setName(s.name);setDescription(s.description??"");setPrice(String(s.price));setDuration(String(s.estimated_duration??60));setCategory(s.category??"Lavagem");setVehicle(s.vehicle_category??"all")};
 const remove=async(s:Service)=>{if(!window.confirm(`Excluir ${s.name}? Essa ação remove o serviço do catálogo e desvincula registros de agendamento que apontam para ele.`))return;setError("");setSaving(true);const refs=await supabase.from("appointment_services").delete().eq("service_id",s.id);if(refs.error){setError(`Não foi possível remover os vínculos dos agendamentos: ${refs.error.message}`);setSaving(false);return}const r=await supabase.from("services").delete().eq("id",s.id);if(r.error)setError(`Não foi possível excluir o serviço: ${r.error.message}`);else{if(editing===s.id)clear();await load()}setSaving(false)};
 const toggle=async(s:Service)=>{const r=await supabase.from("services").update({active:!s.active,updated_at:new Date().toISOString()}).eq("id",s.id);if(r.error)setError(r.error.message);else void load()};
 return <div className="mx-auto max-w-6xl space-y-6 pb-10"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Catálogo</p><h1 className="mt-1 text-3xl font-bold">Serviços</h1><p className="text-sm text-muted-foreground">Preços, duração e categoria de cada serviço.</p></div>{error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
 <div className="grid gap-5 lg:grid-cols-[360px_1fr]"><Card className="rounded-2xl"><CardHeader><h2 className="font-semibold">{editing?"Editar serviço":"Novo serviço"}</h2></CardHeader><CardContent className="space-y-4"><div><Label>Nome</Label><Input className="mt-2" value={name} onChange={e=>setName(e.target.value)} placeholder="Lavagem completa"/></div><div><Label>Descrição</Label><Input className="mt-2" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Inclui lavagem externa..."/></div><div className="grid grid-cols-2 gap-3"><div><Label>Valor</Label><Input className="mt-2" inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="59,90"/></div><div><Label>Duração (min)</Label><Input className="mt-2" type="number" min="5" value={duration} onChange={e=>setDuration(e.target.value)}/></div></div><div><Label>Categoria</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={category} onChange={e=>setCategory(e.target.value)}>{["Lavagem","Adicional","Higienização","Polimento","Detalhamento"].map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Categoria de veículo</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={vehicle} onChange={e=>setVehicle(e.target.value)}>{vehicleOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="flex gap-2"><Button className="flex-1" onClick={()=>void save()} disabled={saving}>{saving?"Salvando...":editing?"Salvar alterações":"Adicionar serviço"}</Button>{editing&&<Button variant="outline" onClick={clear}>Cancelar</Button>}</div></CardContent></Card>
 <div className="space-y-3">{items.length===0?<Card><CardContent className="p-8 text-center text-sm text-muted-foreground">Nenhum serviço cadastrado.</CardContent></Card>:items.map(s=><Card key={s.id} className={"rounded-2xl "+(!s.active?"opacity-60":"")}><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{s.name}</h3><span className="rounded-full bg-muted px-2 py-1 text-[11px]">{s.category||"Serviço"}</span><span className="rounded-full bg-primary/10 px-2 py-1 text-[11px]">{s.vehicle_category==="all"?"Todos":s.vehicle_category}</span></div><p className="mt-1 text-sm text-muted-foreground">{s.description||"Sem descrição"} · {s.estimated_duration??60} min</p></div><div className="flex items-center gap-3"><span className="font-bold">{Number(s.price).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</span><Button size="icon" variant="ghost" onClick={()=>edit(s)}><Pencil/></Button><Button size="sm" variant="outline" onClick={()=>void toggle(s)}>{s.active?"Desativar":"Ativar"}</Button><Button size="icon" variant="ghost" onClick={()=>void remove(s)}><Trash2/></Button></div></CardContent></Card>)}</div></div></div>
}