import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CarFront, Pencil, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { getCurrentCompanyId } from "@/services/company";

export const Route = createFileRoute("/_authenticated/veiculos")({ component: VeiculosPage });
type Vehicle = { id:string; customer_id:string; plate:string; brand:string|null; model:string|null; year:number|null; color:string|null; notes:string|null; current_mileage:number|null };
type Customer = { id:string; name:string; phone:string|null };

function VeiculosPage(){
 const [items,setItems]=useState<Vehicle[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[query,setQuery]=useState(""),[editing,setEditing]=useState<string|null>(null);
 const [customerId,setCustomerId]=useState(""),[plate,setPlate]=useState(""),[brand,setBrand]=useState(""),[model,setModel]=useState(""),[year,setYear]=useState(""),[color,setColor]=useState(""),[mileage,setMileage]=useState(""),[notes,setNotes]=useState("");
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);const id=await getCurrentCompanyId();const [v,c]=await Promise.all([supabase.from("vehicles").select("id,customer_id,plate,brand,model,year,color,notes,current_mileage").eq("company_id",id).order("created_at",{ascending:false}),supabase.from("customers").select("id,name,phone").eq("company_id",id).order("name")]);if(v.error)throw v.error;if(c.error)throw c.error;setItems((v.data??[]) as Vehicle[]);setCustomers((c.data??[]) as Customer[])}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os veículos.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const customerMap=useMemo(()=>new Map(customers.map(c=>[c.id,c])),[customers]);
 const filtered=items.filter(v=>{const q=query.toLowerCase().trim();const c=customerMap.get(v.customer_id);return !q||v.plate.toLowerCase().includes(q)||[v.brand,v.model,v.color,c?.name].filter(Boolean).join(" ").toLowerCase().includes(q)});
 const clear=()=>{setEditing(null);setCustomerId("");setPlate("");setBrand("");setModel("");setYear("");setColor("");setMileage("");setNotes("")};
 const save=async()=>{if(!customerId||!plate.trim())return setError("Informe o cliente e a placa.");try{setSaving(true);setError("");const company_id=await getCurrentCompanyId();const payload={company_id,customer_id:customerId,plate:plate.trim().toUpperCase(),brand:brand.trim()||null,model:model.trim()||null,year:year?Number(year):null,color:color.trim()||null,current_mileage:mileage?Number(mileage):null,notes:notes.trim()||null,updated_at:new Date().toISOString()};const r=editing?await supabase.from("vehicles").update(payload).eq("id",editing):await supabase.from("vehicles").insert(payload);if(r.error)throw r.error;clear();await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o veículo.")}finally{setSaving(false)}};
 const edit=(v:Vehicle)=>{setEditing(v.id);setCustomerId(v.customer_id);setPlate(v.plate);setBrand(v.brand??"");setModel(v.model??"");setYear(v.year?String(v.year):"");setColor(v.color??"");setMileage(v.current_mileage?String(v.current_mileage):"");setNotes(v.notes??"")};
 const remove=async(id:string)=>{if(!window.confirm("Excluir este veículo?"))return;const r=await supabase.from("vehicles").delete().eq("id",id);if(r.error)setError(r.error.message);else void load()};
 return <div className="mx-auto max-w-7xl space-y-6 pb-10"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Operação</p><h1 className="mt-1 text-3xl font-bold">Veículos</h1><p className="text-sm text-muted-foreground">Cadastre vários veículos por cliente e mantenha o histórico organizado.</p></div>{error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
 <div className="grid gap-5 lg:grid-cols-[360px_1fr]"><Card className="rounded-2xl"><CardHeader><h2 className="font-semibold">{editing?"Editar veículo":"Novo veículo"}</h2></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label>Cliente *</Label><select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecione...</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}{c.phone?" · "+c.phone:""}</option>)}</select></div><div className="space-y-2"><Label>Placa *</Label><Input value={plate} onChange={e=>setPlate(e.target.value.toUpperCase())} placeholder="ABC1D23"/></div><div className="grid grid-cols-2 gap-3"><div><Label>Marca</Label><Input className="mt-2" value={brand} onChange={e=>setBrand(e.target.value)}/></div><div><Label>Modelo</Label><Input className="mt-2" value={model} onChange={e=>setModel(e.target.value)}/></div></div><div className="grid grid-cols-2 gap-3"><div><Label>Ano</Label><Input className="mt-2" type="number" value={year} onChange={e=>setYear(e.target.value)}/></div><div><Label>Cor</Label><Input className="mt-2" value={color} onChange={e=>setColor(e.target.value)}/></div></div><div><Label>Quilometragem</Label><Input className="mt-2" type="number" value={mileage} onChange={e=>setMileage(e.target.value)}/></div><div><Label>Observações</Label><Input className="mt-2" value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="flex gap-2"><Button className="flex-1" onClick={()=>void save()} disabled={saving}>{saving?"Salvando...":editing?"Salvar alterações":"Cadastrar veículo"}</Button>{editing&&<Button variant="outline" onClick={clear}>Cancelar</Button>}</div></CardContent></Card>
 <Card className="rounded-2xl"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{items.length} veículo(s)</h2><p className="text-sm text-muted-foreground">Pesquise por placa, cliente, marca ou modelo.</p></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div></CardHeader><CardContent>{loading?<p className="py-8 text-center text-sm text-muted-foreground">Carregando...</p>:filtered.length===0?<div className="py-12 text-center text-muted-foreground"><CarFront className="mx-auto mb-3 h-10 w-10"/><p>Nenhum veículo encontrado.</p></div>:<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(v=><div key={v.id} className="rounded-2xl border p-4 transition hover:shadow-sm"><div className="flex items-start justify-between gap-2"><div><p className="font-bold tracking-wide">{v.plate}</p><p className="text-sm text-muted-foreground">{[v.brand,v.model,v.year].filter(Boolean).join(" · ")||"Veículo sem detalhes"}</p></div><CarFront className="h-5 w-5 text-primary"/></div><p className="mt-3 text-sm font-medium">{customerMap.get(v.customer_id)?.name??"Cliente não encontrado"}</p><p className="text-xs text-muted-foreground">{[v.color,v.current_mileage?v.current_mileage.toLocaleString("pt-BR")+" km":null].filter(Boolean).join(" · ")}</p><div className="mt-4 flex justify-end gap-1"><Button variant="ghost" size="icon" onClick={()=>edit(v)} aria-label="Editar"><Pencil className="h-4 w-4"/></Button><Button variant="ghost" size="icon" onClick={()=>void remove(v.id)} aria-label="Excluir"><Trash2 className="h-4 w-4"/></Button></div></div>)}</div>}</CardContent></Card></div></div>
}
